apply plugin: 'java'

sourceSets {
    main {
        java.srcDirs = ['src']
    }
}

dependencies {
    implementation fileTree(dir: 'libs')

    // api 'com.android.billingclient:billing:7.0.0'
    // Note: no dependency to billingclient, instead only its classes are added as JAR
    // because this is just a plain Java project (billingclient is android AAR)

    implementation "com.google.android:android:4.1.1.4"

    // use projects directly instead of JAR, set up via gradle
    implementation project(":SoomlaAndroidStore")
    implementation project(":soomla-android-core")
}

java {
    targetCompatibility = '1.8'
    sourceCompatibility = '1.8'
}